Repository d610f20/random-activitygen-py, pull requests merged in 2020-03, with the labels that each got.

#1 [args] Add docopt for argument parsing
  randomActivityGen.py
  requirements.txt
Labels: enhancement

#2 Add example network which can be used for testing
  .gitignore
  Statistics.py
  in/example.net.xml
  in/generateNetLinux.sh
  in/generateNetWin.sh
  stats.xml
Labels: documentation

#3 Perlin noise
  Perlin.py
  Statistics.py
  in/example.net.xml
  in/example.stat.xml
  in/example_wavy.net.xml
  randomActivityGen.py
  requirements.txt
Labels: enhancement

#6 [City-gates] Determine and create city gates
  .gitignore
  randomActivityGen.py
Labels: enhancement

#9 [City gates] Better handling of the stat xml and inserts missing streets
  in/example.stat.xml
  perlin.py
Labels: bug, enhancement
